Use bioconductor/ml-verse base image to support GPUs
Revert Python customizations to allow reticulate to function more reliably

Unset PIP_USER due to error in virtualenv:
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.